name: CI

on:
  push:
    branches: [master, main, develop, 'feature/*']
  pull_request:
    branches: [master, main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Lint & Format check
        run: |
          yarn prettier --check .
          yarn eslint .

      - name: Type check
        run: yarn type-check

      - name: Run tests
        run: yarn test

      - name: Build packages
        run: yarn build

      - name: Test playground (only on main/master)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          cd playground/vite-plugin
          yarn install
          yarn build
